apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: vote



  
